### ISSUE TITLE
pip installed 2.2.135 reports module not found

### ISSUE THREAD

**Issue by JixianLi** [sci-visus/OpenVisus#260]
Running command `python -m OpenVisus configure`

From file `"OpenVisus/__init__.py"` line 6:
`from OpenVisus.VisusKernelPy   import *`
`ModuleNotFoundError: No module named 'OpenVisus.VisusKernelPy'`

Python version 3.12.3
pip version 24.3.1
Both are clean (fresh setup from a virtual environment)

installation command
`pip install OpenVisus`

This error also exists when trying `import OpenVisus as ov` from a Python script.

Did the wheel not include all the required files?

**Comment by scrgiorgio** [comment]
@JixianLi should be solved. If so please close

**Comment by JixianLi** [comment]
@scrgiorgio 
I did `pip cache purge` and `pip install OpenVisus`. The issue persists.
I compare the `site-packages/OpenVisus` directory with a 3.10 version that's working for me.
The 3.12 directory has the following files:
```
__pycache__
dataset.py
gui.py
image_utils.py
s3.py
scripting_node.py
setup.py
utils.py
viewer.py
convert.py
__init__.py
__main__.py
PyMultipleDataset.h
VisusDataflowPy.i
VisusDbPy.i
VisusGuiPy.i
VisusKernelPy.i
VisusNodesPy.i
VisusPy.common
CMakeLists.txt
```
The 3.10 directory has the following files:
```
__pycache__
include
lib
datasets
bin
Samples
Copyrights
gui.py
image_utils.py
s3.py
scripting_node.py
setup.py
utils.py
viewer.py
visus.config
convert.py
dataset.py
__init__.py
__main__.py
_VisusKernelPy.so
_VisusNodesPy.so
_VisusGuiPy.so
_VisusDbPy.so
_VisusDataflowPy.so
LICENSE
QT_VERSION
README.md
VisusDataflowPy.py
VisusDbPy.py
VisusGuiPy.py
VisusKernelPy.py
VisusNodesPy.py
```
basically, the required modules in the `__init__.py` changed from `.py` + `.so` to `.i`. 
I'm not sure how `.i` works in Python module loading. 
But my Python can't find the modules from those files.
Did I miss some steps in setting things up?

**Comment by scrgiorgio** [comment]
can you try again @JixianLi ?

**Comment by JixianLi** [comment]
Works perfectly. Thank you. Issue closed.
